require("dotenv").config();

const PORT = process.env.PORT;
const MONGODB_URI = process.env.MONGODB_URI;
const SECRET_KEY = process.env.SECRET_KEY;
const CLIENT_URL1 = process.env.CLIENT_URL1;
const CLIENT_URL2 = process.env.CLIENT_URL2;
const EMAIL_ID = process.env.EMAIL_ID;
const EMAIL_PASS = process.env.EMAIL_PASS;
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const CLOUDINARY_ASSET_FOLDER = process.env.CLOUDINARY_ASSET_FOLDER;
const CLOUDINARY_UPLOAD_PRESET = process.env.CLOUDINARY_UPLOAD_PRESET;

module.exports = {
  PORT,
  MONGODB_URI,
  SECRET_KEY,
  CLIENT_URL1,
  CLIENT_URL2,
  EMAIL_ID,
  EMAIL_PASS,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_ASSET_FOLDER,
  CLOUDINARY_UPLOAD_PRESET,
};
